# Generated by Django 3.2.5 on 2021-07-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPercentange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='value1',
            new_name='angina',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='value2',
            new_name='chestpain',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='cholestorol',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='heartbeats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='major_vessels',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='slope',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='st_depression',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='thalassemia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HeartBeat',
        ),
        migrations.AddField(
            model_name='riskpercentange',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk', related_query_name='risk', to='patient.patient'),
        ),
    ]
