# Generated by Django 3.2.5 on 2021-07-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0002_patient_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskPercentange',
        ),
    ]
