# Generated by Django 3.2.5 on 2021-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthTracker', '0003_delete_riskpercentange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='angina',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_pressure',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chestpain',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cholestorol',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='heartbeats',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='major_vessels',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='slope',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='st_depression',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='thalassemia',
            field=models.IntegerField(default=-1),
        ),
    ]
