# Generated by Django 3.2.5 on 2021-07-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210710_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskpercentange',
            name='value',
            field=models.FloatField(),
        ),
    ]
